### ISSUE TITLE
SSL certificate expired?

### ISSUE THREAD

**Issue by weilu** [GlobalDataLab/R-data-api#1]
Hi,

When I tried to pull data using the R package I got the following error. It started happening this year, so perhaps the SSL certificate needs to be updated?

```
Error in req_perform(req) : Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! SSL peer certificate or SSH remote key was not OK: [globaldatalab.org] server certificate verification failed. CAfile: none CRLfile: none
Error in `req_perform()`:
Error in `req_perform()`:
! Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! SSL peer certificate or SSH remote key was not OK: [globaldatalab.org] server certificate verification failed. CAfile: none CRLfile: none
```

Code for replication: 
```R
library(magrittr)

sess <- sess %>%
    set_dataset('shdi') %>%
    set_countries(c('BEL', 'LUX', 'NLD')) %>%
    set_indicators(c('healthindex', 'edindex', 'incindex')) %>%
shdi_benelux <- gdl_request(sess)
```

**Comment by AaronVanGeffen** [comment]
Thanks for filing an issue. This is odd. The R package is using our website as its back-end, which is working on my end at least (https://globaldatalab.org/). The following also works on my end:

```
sess <- gdl_session('MY_SECRET_TOKEN')
sess <- sess |>
    set_dataset('shdi') |>
    set_countries(c('BEL', 'LUX', 'NLD')) |>
    set_indicators(c('healthindex', 'edindex', 'incindex')) |>
shdi_benelux <- gdl_request(sess)
```

Could I ask you for some more information about your environment? What OS/platform are you using, along with what version of R?

**Comment by weilu** [comment]
You are right! I tried it on my local environment and it worked. The SSL error was only happening in my company's Azure databricks. Might be network rules that might have caused it. Closing this. Thank you for your prompt help!
